export const DELETE_MOVIE = "DELETE_MOVIE";
export const FILTER_MOVIE = "FILTER_MOVIE";
export const REMOVE_FILTER_MOVIE = "REMOVE_FILTER_MOVIE";
export const ADD_FILTER_MOVIE = "ADD_FILTER_MOVIE";
export const HANDLE_LIKE = "HANDLE_LIKE";
